# Generated by Django 3.1.7 on 2021-04-25 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_mgmt_system', '0003_auto_20210418_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='stream',
            name='cordinator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='student_mgmt_system.cordinator'),
        ),
    ]
