# Generated by Django 3.1.7 on 2021-04-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_mgmt_system', '0004_auto_20210425_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('club_email', models.EmailField(max_length=254)),
                ('student', models.ManyToManyField(related_name='student_club', to='student_mgmt_system.Student')),
            ],
        ),
    ]
